"""empty message

Revision ID: 972d0d68229
Revises: 51dac2f603c9
Create Date: 2014-09-03 20:01:00.505945

"""

# revision identifiers, used by Alembic.
revision = '972d0d68229'
down_revision = '51dac2f603c9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
